title: n8henrie.com
author: Nathan Henrie
email: nate@n8henrie.com
description: >
  Technology, medicine, science, superstition... and having fun.
  Brought to you by Nathan Henrie.
url: "https://n8henrie.com"
twitter_username: n8henrie
github_username:  n8henrie
timezone: America/Denver
encoding: utf-8

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

permalink: /:year/:month/:title/

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

show_drafts: false

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

sass:
  sass_dir: _sass
  style: compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true

paginate: 8

exclude: [tmp,import_versions,Makefile,todo.md,vendor,_drafts/template.md]
